[[pages]]
path = "home.py"
name = "SPbLitGuide 1999–2020"
icon = "🏠"

[[pages]]
name = "Dataset"
icon = ":books:"
is_section = true

[[pages]]
path = "pages/description.py"
name = "Description"
icon = ":books:"
in_section = true

[[pages]]
path = "pages/datamodel.py"
name = "Data Modeling"
icon = ":file_cabinet:"
in_section = true

[[pages]]
path = "pages/processing.py"
name = "Data Processing"
icon = ":file_cabinet:"
in_section = true

[[pages]]
path = "pages/eda.py"
name = "Exploratory Data Analysis"
icon = ":bar_chart:"
in_section = false
is_section = true

[[pages]]
path = "pages/activity.py"
name = "EDA: Events' Distribution"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/person_activity.py"
name = "EDA: People's Activity"
icon = ":chart_with_upwards_trend:"


[[pages]]
name = "Mapping Literary Space"
icon = ":world_map:"
in_section = false
is_section = true

[[pages]]
path = "pages/map.py"
name = "Geographical Distribution"
icon = ":world_map:"

[[pages]]
path = "pages/map_chart.py"
name = "Event Frequency's Mapping"
icon = ":world_map:"

[[pages]]
path = "pages/heatmap.py"
name = "Heat Map of Events' Frequency"
icon = ":world_map:"

[[pages]]
path = "pages/heatmap_year.py"
name = "Dynamic Heatmap"
icon = ":world_map:"

[[pages]]
name = "Network Analysis"
is_section = true
icon = ":people_holding_hands:"

[[pages]]
path = "pages/graph.py"
name = "Literary Interaction Network"
icon = ":linked_paperclips:"
in_section = true

[[pages]]
path = "pages/network_2014.py"
name = "Literary Communities"
icon = ":linked_paperclips:"
in_section = true

[[pages]]
path = "pages/network.py"
name = "Full Network"
icon = ":linked_paperclips:"
in_section = true

[[pages]]
path = "pages/test.py"
name = "Edit data"
icon = ":pencil2:"
in_section = false



