[[pages]]
path = "home.py"
name = "SPbLitGuide 1999–2020"
icon = "🏠"

[[pages]]
path = "pages/description.py"
name = "Dataset"
icon = ":books:"

[[pages]]
path = "pages/datamodel.py"
name = "Model"
icon = ":file_cabinet:"

[[pages]]
path = "pages/eda.py"
name = "Exploratory Data Analysis"
icon = ":bar_chart:"
is_section = true

[[pages]]
path = "pages/activity.py"
name = "EDA: Events' Distribution"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/person_activity.py"
name = "EDA: People's Activity"
icon = ":chart_with_upwards_trend:"


[[pages]]
name = "Visualisation"
icon = ":world_map:"
in_section = false
is_section = true

[[pages]]
path = "pages/map.py"
name = "Geographical Distribution"
icon = ":world_map:"

[[pages]]
path = "pages/map_chart.py"
name = "Event Frequency's Mapping"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/heatmap.py"
name = "Heat Map of Events' Frequency"
icon = ":world_map:"

[[pages]]
path = "pages/graph.py"
name = "Literary Interaction Network"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/test.py"
name = "Edit data"
icon = ":pencil2:"
in_section = false



